<a href="https://colab.research.google.com/github/Nyota-Lab/torch/blob/Primeros-Pasos/Primeros_Pasos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Primeros pasos uso de Pytorch
* Importamos Pytorch

In [0]:
import torch
import numpy as np
import pandas as pd


##Trabajando con Tensores

* Para verificar la version de Pytorch

In [2]:
torch.__version__

'1.4.0'

* Creamos nuestro primer Tensor, en este caso el método .ones nos genera uno compuesto de números 1 de acuerdo a la dimensión especificada

In [3]:
tensor_a = torch.ones(2,2)
tensor_a

tensor([[1., 1.],
        [1., 1.]])

* Con Tensor generamos uno nuevo pero con valores aleatorios
* Con .uniform_ modificamos al tensor_b para que los valores estén entre 0 y 1

In [4]:
tensor_b = torch.Tensor(2,2)
print(tensor_b)
tensor_b.uniform_(0,1)

tensor([[3.2297e-35, 0.0000e+00],
        [3.7835e-44, 0.0000e+00]])


tensor([[0.7960, 0.2267],
        [0.2607, 0.0638]])

* Podemos simplificar estos dos pasos con el método rand directamente

In [5]:
tensor_c = torch.rand(2,2)
tensor_c

tensor([[0.6720, 0.3029],
        [0.8212, 0.9450]])

* Con los Tensores tambien podemos ralizar las operaciones matemáticas básicas por ejemplo una suma

In [6]:
result1 = tensor_b + tensor_c
result1

tensor([[1.4681, 0.5296],
        [1.0820, 1.0088]])

* Además podemos ver la dimension del tensor el cual es un arreglo similar a una matriz para poder realizar las operaciones que nos exijan una dimension específica
* Tambuen es posible redimensionarlos para poder hacer operaciones entre matrices por ejemplo

In [7]:
print(result1.shape)
reshaped = result1.view(1,4)
reshaped

torch.Size([2, 2])


tensor([[1.4681, 0.5296, 1.0820, 1.0088]])

* Podemos además crear tensores con los datos específicos organizandolos por filas y separandolos con coma
* Para acceder a uno de los valores del tensor solo debemos dar su posicion con fila y columna
* Para resaignar un valor usamos nuevamente la ubicacion de fila y columna y reasignamos como si fuera una variable normal

In [8]:
points = torch.tensor([[1.0, 2.0],[3.0, 4.0]])
print(points)
print(points[0][1])
points[0][1]=2.5
print(points)

tensor([[1., 2.],
        [3., 4.]])
tensor(2.)
tensor([[1.0000, 2.5000],
        [3.0000, 4.0000]])


* Tambien es util saber la forma en la que se están guardando los elementos del tensor, eso lo hacemos con storage

In [9]:
points.storage()

 1.0
 2.5
 3.0
 4.0
[torch.FloatStorage of size 4]

* Ademas podemos observar la forma en como se cambia de un elemento a otro con el método stride, el cual nos regresa 2 números, el primero nos dice cuantos elementos lee en el primer elemento(numero de objetos en una fila para simplificarlo) y el segundo es el momento en que cambia de elemento(pasa a la siguente fila)

In [10]:
points, points.stride()

(tensor([[1.0000, 2.5000],
         [3.0000, 4.0000]]), (2, 1))

* Además podemos transponer los tensores para algún tipo de operacion que se necesite hacer

In [11]:
p_t = points.t()
p_t, p_t.stride()

(tensor([[1.0000, 3.0000],
         [2.5000, 4.0000]]), (1, 2))

* Otra manipulacion de los tensores es agregandole dimensiones al mismo siendo 0 una dimension en horizontal y 1 en vertical

In [12]:
tensor_x = torch.tensor([1,2,3,4])
print(tensor_x, torch.unsqueeze(tensor_x, 0))
tensor_x2 = torch.tensor([1,2,3,4])
tensor_x2, torch.unsqueeze(tensor_x2, 1)


tensor([1, 2, 3, 4]) tensor([[1, 2, 3, 4]])


(tensor([1, 2, 3, 4]), tensor([[1],
         [2],
         [3],
         [4]]))

In [13]:
numpyArray = np.random.randn(2,2)
print(numpyArray)
from_numpy = torch.from_numpy(numpyArray)
print(from_numpy)

[[ 2.09416315  0.04953826]
 [-0.90634943 -0.21120875]]
tensor([[ 2.0942,  0.0495],
        [-0.9063, -0.2112]], dtype=torch.float64)


#Representar datos con tensores

---



* Podemos obtener datos estadísticos de los tensores como por ejemplo la media
  * En este caso tenemos algunas puntualizaciones
    * La media sin especificar una dimensión nos entrega un solo valor
    * La media con dimensión cero nos da como resultado el cálculo en columnas
    * La media con dimensión uno nos da como resultado el cálculo en filas


In [14]:
print(from_numpy)
print(torch.mean(from_numpy))
print(torch.mean(from_numpy, dim=0))
print(torch.mean(from_numpy, dim=1))

tensor([[ 2.0942,  0.0495],
        [-0.9063, -0.2112]], dtype=torch.float64)
tensor(0.2565, dtype=torch.float64)
tensor([ 0.5939, -0.0808], dtype=torch.float64)
tensor([ 1.0719, -0.5588], dtype=torch.float64)


* La misma lógica se puede usar para la desviacion estandar y otros cálculos estadísticos en el tensor

In [15]:
print(from_numpy)
print(torch.std(from_numpy))
print(torch.std(from_numpy, dim=0))
print(torch.std(from_numpy, dim=1))

tensor([[ 2.0942,  0.0495],
        [-0.9063, -0.2112]], dtype=torch.float64)
tensor(1.2898, dtype=torch.float64)
tensor([2.1217, 0.1844], dtype=torch.float64)
tensor([1.4458, 0.4915], dtype=torch.float64)


* Los tensores tambien se pueden guardar y cargar en el disco virtual de colab

In [0]:
torch.save(from_numpy, 'tensor.t')

In [17]:
load = torch.load('tensor.t')
load

tensor([[ 2.0942,  0.0495],
        [-0.9063, -0.2112]], dtype=torch.float64)

* Tomemos un dataset desde github para iniciar con nuestros modelos

In [20]:
url = 'https://raw.githubusercontent.com/amanthedorkknight/fifa18-all-player-statistics/master/2019/data.csv'
dataframe = pd.read_csv(url)
dataframe

Unnamed: 0      ID  ... GKReflexes  Release Clause
0               0  158023  ...        8.0         €226.5M
1               1   20801  ...       11.0         €127.1M
2               2  190871  ...       11.0         €228.1M
3               3  193080  ...       94.0         €138.6M
4               4  192985  ...       13.0         €196.4M
...           ...     ...  ...        ...             ...
18202       18202  238813  ...        9.0           €143K
18203       18203  243165  ...       12.0           €113K
18204       18204  241638  ...       13.0           €165K
18205       18205  246268  ...        9.0           €143K
18206       18206  246269  ...        9.0           €165K

[18207 rows x 89 columns]

* Para saber el nombre de las features usamos .columns en nuestro dataframe

In [28]:
dataframe.columns

Index(['Unnamed: 0', 'ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag',
       'Overall', 'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingT

* Creamos un subset con algunas de las columnas de nuestro dataframe
* De este subset solo tomamos desde la edad hacia delante ya que la primera columna es la que vamos a intentar explicar
* Lo instanciamos en una variable y convertimos los datos en un tensor, ademas lo forzamos a que sea de tipo float
* Por último verificamos su dimensión y su tipo
* Adicionalmente podemos tener problemas mas adelante con los valores faltantes, por lo cual vamos a eliminarlos directamente de nuestro subset

In [44]:
subset = dataframe[['Overall', 'Age', 'International Reputation', 'Weak Foot',
       'Skill Moves']].dropna(axis=0, how='any')
columns = subset.columns[1:]
players = torch.tensor(subset.values).float()
players.shape, players.type()

(torch.Size([18159, 5]), 'torch.FloatTensor')

* Al instanciar en players como un tensor tambien se incluyó la columna de 'Overall' por lo tanto vamos a sacarla
* una vez transformado en tensor no podemos usar el método drop

In [45]:
data = players[:, 1:]
data, data.shape

(tensor([[31.,  5.,  4.,  4.],
         [33.,  5.,  4.,  5.],
         [26.,  5.,  5.,  5.],
         ...,
         [16.,  1.,  3.,  2.],
         [17.,  1.,  3.,  2.],
         [16.,  1.,  3.,  2.]]), torch.Size([18159, 4]))

* Ya tenemos las features que vamos a usar para explicar nuestro target, pero primero vamos a instanciarlo.

In [46]:
target = players[:, 0]
target, target.shape

(tensor([94., 94., 92.,  ..., 47., 47., 46.]), torch.Size([18159]))

* Para verificar la salud de nuestros datos podemos realizar un promedio

In [47]:
target_mean = torch.mean(target)
print(target_mean)
data_mean = torch.mean(data, dim=0)
print(data_mean)

tensor(66.2499)
tensor([25.1225,  1.1132,  2.9473,  2.3613])


* Como observamos anteriormente vamos a sacar la desviacion estandar de cada uno

In [49]:
target_std = torch.std(target)
print(target_std)
data_std = torch.std(data, dim=0)
print(data_std)

tensor(6.9146)
tensor([4.6706, 0.3940, 0.6605, 0.7562])


* Ya con los valores de la media y la desviacion estandar podemos normalizar los valores de nuestro subset

In [50]:
norm = (data-data_mean)/torch.sqrt(data_std)
norm

tensor([[ 2.7196,  6.1919,  1.2953,  1.8845],
        [ 3.6450,  6.1919,  1.2953,  3.0345],
        [ 0.4060,  6.1919,  2.5258,  3.0345],
        ...,
        [-4.2211, -0.1804,  0.0648, -0.4155],
        [-3.7584, -0.1804,  0.0648, -0.4155],
        [-4.2211, -0.1804,  0.0648, -0.4155]])

* Vamos a clasificar a nuestros jugadores por grupos
  * ge = grater or equal
  * gt = greater than
  * lt = lower than
  * le = lower or equal

* Explicando las últimas dos lineas:
  * Vamos a organizar todos los valores de cada una de las variables (columns, goodMean, averageMean, notSoGoodMean)
  * Una vez organizados los imprimimos en pantalla, {inicio:final.numero de digitos float}

In [75]:
good = data[torch.ge(target, 85)]
average = data[torch.gt(target, 70) & torch.lt(target, 85)]
notSoGood = data[torch.le(target, 85)]

goodMean = torch.mean(good, dim = 0)
averageMean = torch.mean(average, dim = 0)
notSoGoodMean = torch.mean(notSoGood, dim = 0)

for i, args in enumerate(zip(columns, goodMean, averageMean, notSoGoodMean)):
  print('{:25}{:6.2f}{:6.2f}{:6.2f}'.format(*args))

Age                       28.35 27.23 25.11
International Reputation   3.38  1.36  1.10
Weak Foot                  3.45  3.11  2.95
Skill Moves                3.04  2.75  2.36
